base: 'https://www.voltetaicerveseta.es/'
baseVariants:
  -
    base: 'https://boilerplate.ddev.site/'
    condition: 'applicationContext == "Development/Local"'
languages:
  -
    title: Spanish
    enabled: true
    languageId: 0
    base: /
    typo3Language: es
    locale: eu_ES
    iso-639-1: es
    navigationTitle: Español
    hreflang: es-es
    direction: ltr
    flag: es
    websiteTitle: ''
rootPageId: 1
websiteTitle: 'Volteta i Cerveseta'
