base: 'https://boilerplate.ddev.site/voltetaicerveseta'
errorHandling: {  }
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-gb
    direction: ltr
    flag: gb
rootPageId: 1
routes: {  }
